server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: incidents
          uri: lb://INCIDENTS
          predicates:
            - Path=/api/v1/incident/**
        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/api/v1/authentication/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true